import type { Metadata } from "next";
import "./../globals.css";
import "@fortawesome/fontawesome-free/css/all.min.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "C1 COIN",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

const ralewayFont = localFont({
  src: [
    {
      path: "../fonts/Raleway-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../fonts/Raleway-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../fonts/Raleway-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/Raleway-ExtraBold.ttf",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--raleway-font",
});

const geistFont = localFont({
  src: [
    {
      path: "../fonts/Geist-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../fonts/Geist-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/Geist-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../fonts/Geist-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../fonts/Geist-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--tajawal-font",
});

export default async function RootLayout(props: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const params = await props.params;

  const { children } = props;

  const { locale } = params;

  if (!locale || (locale != "en" && locale != "tr")) {
    notFound();
  }

  const messages = await getMessages({ locale });

  return (
    <html lang={locale} className="overflow-x-hidden">
      <body
        className={`relative min-h-full min-w-full overflow-x-hidden bg-white ${ralewayFont.variable} ${geistFont.variable}`}
      >
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
